nrfconnect/Asset-Tracker-Template

- app/src/modules/app/app.c
- tests/module/app/CMakeLists.txt
- tests/module/app/src/main.c
App module should respond to cloud events.
Also rename connected to cloud_connected etc.
> modules: app: fix behaviour

- tests/on_target/tests/test_functional/test_fota.py
Fota resumption is currently broken.
> tests: on_target: ski fota resumption

- .github/workflows/target-test.yml
Upload elf file to memfualt in CI.
> workflows: target-test: upload elf to memfault

- .github/workflows/sonarcloud.yml
- sonar-project.properties
> workflows: sonarcloud: enable sonarcloud

- tests/on_target/tests/test_functional/test_fota.py
> tests: on_target: new mfw bundle IDs

- .github/workflows/compliance.yml
Use zephyr compliance requirements.txt.
> workflows: compliance: fix requirements

- app/src/modules/cloud/cloud_module.c
> modules: cloud: Address static code analysis issues

- tests/on_target/tests/test_functional/test_location.py
> tests: on_target: add location test

- tests/on_target/tests/test_functional/test_location.py
> test: on_target: small fix location

- .github/workflows/test_docker_publish.yml
Add workflow for test docker image.
> workflows: add workflow for test docker image

- .github/workflows/target-test.yml
- tests/on_target/README.md
> workflows: target-test: use att test docker

- tests/on_target/tests/test_functional/test_sampling.py
Increase timeout for test_sampling.py
> tests: Increase timeout for test_sampling.py

- tests/on_target/tests/test_functional/test_sampling.py
> tests: on_target: fix location regex

- README.md
- sonar-project.properties
> tree: adapt to new org

- app/src/modules/cloud/cloud_module.c
- app/src/modules/fota/fota.c
- app/src/modules/shell/shell.c
- tests/on_target/tests/test_functional/test_fota.py
Add test for FOTA cancellation from cloud.
Reinstate the LTE connection drop test.
> tests: on_target: Add test for FOTA cancellation from cloud

- .github/workflows/target-test.yml
> tests: on_target: fix nightly

- .github/workflows/target-test.yml
> tests: on_target: fix nightly more

- .github/workflows/target-test.yml
> tests: on_target: small fix

- .github/workflows/target-test.yml
> tests: on_target: small fix.

- app/src/common/message_channel.h
- app/src/main.c
- app/src/modules/fota/fota.c
- app/src/modules/network/network.c
Fix bug in fota.c where the state pointer wasn't cast properly. Resulting in an invalid state transition.
> modules: fota: fix bug in fota.c

- app/src/main.c
- app/src/modules/cloud/cloud_module.c
- app/src/modules/fota/fota.c
- app/src/modules/led/led.c
- app/src/modules/location/location.c
- app/src/modules/network/network.c
- app/src/modules/power/power.c
Check all non-void functions' return values, or explicitly void where error handling is not relevant.
> modules: Add return value checks

- .github/workflows/target-test.yml
Disable ppk test momentarily, fix pending.
> workflows: target-test: disable ppk test

- .github/workflows/attach_release_assets.yml
> workflows: fix release

- .github/workflows/build.yml
> workflows: build: small fix

- docs/common/test_and_ci_setup.md
> docs: add ci docs.

- docs/common/configurability.md
- docs/common/location_services.md
- docs/common/test_and_ci_setup.md
- docs/modules/button.md
configurability and location services docs.
> docs: more docs

- tests/on_target/tests/test_functional/test_shell.py
> tests: on_target: small fix shell test

- README.md
- docs/common/configurability.md
Add docs for configuring update interval with rest.
> docs: config with rest api

- docs/modules/fota.md
Add documentation for the FOTA Module.
> docs: Add FOTA module docs

- docs/modules/fota.md
> docs: Fix FOTA state diagram

- .github/workflows/build.yml
> workflow: small fix in build workflow

- docs/modules/fota.md
Add some more detail on the FOTA module operations.
> docs: fota: Add more details to FOTA module documentation

- app/CMakeLists.txt
- app/src/modules/cloud/CMakeLists.txt
- app/src/modules/cloud/Kconfig.cloud
- app/src/modules/fota/Kconfig.fota
- app/src/modules/location/Kconfig.location
Move CMake warning
---
Make modules optional
> modules: Minor fixes

- app/src/modules/location/location.c
Add SMF state machine to location module.
> modules: location: use SMF

- README.md
- tests/on_target/scripts/parse_memory_stats.py
Add thingy91x device name to memory labels.
> README: add thingy91x to memory labels

- README.md
- docs/common/location_services.md
- docs/modules/location.md
> docs: add location module docs

- west.yml
Update to latest sdk-nrf reference.
> manifest: Update sdk-nrf reference

- .github/workflows/build.yml
- .github/workflows/sonarcloud.yml
- tests/module/README.md
Remove bsec and some small cleanup.
> tree: cleanup, remove bsec

- .github/workflows/build.yml
> workflows: build: skip 9151 on pr

- tests/on_target/tests/conftest.py
- tests/on_target/tests/test_ppk/test_power.py
> workflows: target-test: fix ppk test

- tests/on_target/tests/test_functional/test_fota.py
App fota should belong to "slow" tests.
> tests: on_target: mark app fota test as "slow"

- tests/module/location/src/location_module_test.c
Add one test case for the location handler.
> tests: module: more location unittest

- README.md
- docs/common/architecture.md
- docs/common/business_logic.md
Add docs about the template architecture.
Only zbus is covered to begin with.
> docs: Add Architecture documentation

- app/src/modules/location/location.c
> modules: location: fix log message

- docs/common/getting_started.md
> docs: getting_started: small integrations and fix

- README.md
- tests/on_target/scripts/memory_plot_generator.py
- tests/on_target/scripts/parse_memory_stats.py
- tests/on_target/scripts/update_memory_badges.sh
Save history of ram and flash usage and link to readme.
> ci: add memory history plot to readme

- .github/workflows/attach_release_assets.yml
Small fix release attach assets.
> workflows: fix release attach assets

- docs/common/getting_started.md
Fixed a small typo on Getting Started.
> Docs: Fixed typo in getting_started.md

- README.md
- docs/common/nrfcloud_fota.md
- tests/on_target/utils/nrfcloud.py
Add instructions on how to manage nrfcloud fota via rest api.
> docs: add nrfclouud fota docs

- docs/common/configurability.md
Add warning regarding the device config section in nrf cloud
> docs: Add warning regarding the device config section in nrf cloud

- docs/common/configurability.md
Simplify warning by removing HTML.
> docs: Simplify warning

- tests/on_target/scripts/memory_plot_generator.py
> docs: improve memory plots

- .github/actions/build-step/action.yml
- .github/workflows/attach_release_assets.yml
- .github/workflows/build.yml
- .github/workflows/publish-symbol-files-to-memfault.yml
- .github/workflows/target-test.yml
- tests/on_target/tests/conftest.py
- tests/on_target/tests/test_functional/test_memfault.py
Remove memfault from normal build and add to debug build.
> workflows: remove mflt from normal build

- docs/common/getting_started.md
- tests/on_target/scripts/memory_plot_generator.py
Small fixes to getting started guide.
> docs: small fixes

- app/sysbuild.conf
Remove unused file sysbuild.conf
> Remove unused file sysbuild.conf

- app/src/modules/fota/Kconfig.fota
> modules: fota: increase APP_FOTA_THREAD_STACK_SIZE

- app/src/main.c
- app/src/modules/cloud/cloud_module.c
- app/src/modules/environmental/environmental.c
- app/src/modules/fota/fota.c
- app/src/modules/location/location.c
- app/src/modules/network/network.c
- app/src/modules/power/power.c
- tests/module/location/CMakeLists.txt
- tests/module/location/src/location_module_test.c
- Check retval for task_wdt_add() in all modules
- Make location module not depend on the network module
> modules: Various unifications

- app/src/main.c
Add led patterns. 10 repetitions each.
Yellow on disconnected, green on sampling, light green on low power. Purple indefinite on fota downloading.
> app: main: rework led patterns

- app/src/modules/led/led.c
Led module can be simplified a bit, remove some confusion.
> modules: led: remove unnecesary complexity

- docs/common/test_and_ci_setup.md
- tests/on_target/README.md
> docs: improve ci docs

- docs/common/nrfcloud_fota.md
Wrong fota bin path in the docs.
> docs: fix fota bin

- tests/on_target/tests/test_functional/test_shell.py
Increase timeout on waiting for string.
> tests: on_target: increase test timeout

- .github/workflows/build.yml
- .github/workflows/target-test.yml
- docs/patches/dummy-module.patch
- tests/on_target/tests/conftest.py
- tests/on_target/tests/test_functional/test_config.py
- tests/on_target/tests/test_functional/test_fota.py
- tests/on_target/tests/test_functional/test_memfault.py
- tests/on_target/tests/test_functional/test_patched.py
- tests/on_target/tests/test_functional/test_sampling.py
Build and test patches documented in the customization guide in CI to verify that they always work.
> ci: Test patches in CI

- README.md
- docs/common/getting_started.md
Missing --shell in nrfutil toolchain manger command.
> docs: fix nrfutil toolchain manger command

- .github/workflows/ai-review.yaml
> workflows: fix ai review

- tests/on_target/tests/test_functional/test_config.py
- tests/on_target/tests/test_functional/test_fota.py
- tests/on_target/tests/test_functional/test_memfault.py
- tests/on_target/tests/test_functional/test_patched.py
- tests/on_target/tests/test_functional/test_sampling.py
- tests/on_target/tests/test_functional/test_shell.py
- tests/on_target/utils/uart.py
Tests have been unstable due to networking.
Add retry mechanism to reduce instability.
> tests: on_target: add retry mechanism on connect

- .github/workflows/verify-state-machine.yml
> workflows: add a verify state machine workflow

- tests/on_target/utils/uart.py
att_network disconnect is needed. Otherwise device retries to connect.
> tests: on_target: fix uart factory reset

- README.md
- docs/common/getting_started.md
Add more details to getting started steps.
> docs: Add more details to gettings started steps

- docs/common/test_and_ci_setup.md
Minor updates, mostly styling.
> docs: Minor updates to test and CI section

- docs/common/customization.md
- scripts/rename_patch.py
Add script to add and rename the dummy patch file.
> docs: Add script to add and rename the dummy patch file

- .github/workflows/attach_release_assets.yml
> workflows: fix release cycle

- .github/workflows/target-test.yml
> workflow: missing input param

- app/src/modules/power/power.c
> modules: power: fix trace level Kconfig

- app/src/main.c
Current light green color is very bad for user experience. Change to blue color instead.
> modules: led: blink blue in low power

- README.md
> readme: fix wrong link

- README.md
- docs/common/configuration.md
> docs: add led colors docs

- app/CMakeLists.txt
- app/config/memfault_platform_config.h
- docs/common/customization.md
- docs/common/getting_started.md
Fix memfault event storage full.
By increasing storage and upload frequency and sampling interval.
> app: memfault: fix memfault event storage full

- app/src/modules/location/Kconfig.location
Increase stack size of the location module to prevent crash.
> modules: location: Increase stack size for location module

- patches/magnetometer.patch
> patches: fix magnetometer patch

- .github/workflows/build.yml
- tests/on_target/tests/test_functional/test_patched.py
Patched firmware keeps failing, rework needed.
Pause in CI for now.
> ci: quarantine patched fw build

- README.md
Fix wrong path for system overview image.
> readme: fix path for system overview image

- .github/workflows/sonarcloud.yml
- tests/module/README.md
- tests/module/cloud/src/cloud_module_test.c
> tests: module: add asan

- .github/workflows/sonarcloud.yml
Enable leak sanitizer to check for heap memory leaks. Enable undefined behavior sanitizer to check for
undefined behaviour during program execution.
> workflows: sonarcloud: add lsan and ubsan

- .github/workflows/target-test.yml
- tests/on_target/tests/test_ppk/test_power.py
> tests: on_target: make ppk test more stable

- app/src/modules/network/network.c
- tests/module/network/src/main.c
- west.yml
> manifest: Update nrf-sdk reference

- app/src/modules/network/network.c
- west.yml
Update sdk-nrf reference to v3.1.0
> manifest: Update sdk-nrf reference to v3.1.0

- tests/on_target/tests/test_functional/test_config.py
Fix test string. Log output was changed in recent commit.
> tests: on_target: Fix test string

- .github/workflows/compliance.yml
> ci: always run compliance on pr

- docs/common/release.md
Add ext_gnss 9151dk board to release document.
> docs: update relase.md

- tests/on_target/tests/test_functional/test_fota.py
We are seeing issues with multiple delta fotas back to back. Add a nightly test case that goes from 2.0.2 to 2.0.2-FOTA-TEST, and back to 2.0.2.
> tests: on_target: add delta fota back-to-back

- tests/state_machines/verify_machine.py
Use gpt5 and fixed seed for deterministic preference.
> tests: use gpt5 for state machine verify
