nrfconnect/Asset-Tracker-Template

tests/on_target/tests/conftest.py
t91x_board is wrongly scoped to module, should be function. This makes uart timeout prematurely.
=> tests: on_target: t91x_board scope to function

app/src/modules/app/app.c
Add missing state transition.
For delta updates we go straight to rebooting state after the download has been downloaded.
=> modules: app: Add missing state transition

.github/workflows/ai-review.yaml
Try openai instead of anthropic.
=> workflows: ai-review: use openai

app/src/modules/app/app.c, app/src/modules/cloud/cloud_module.c, app/src/modules/location/location.c, tests/module/app/src/main.c, tests/module/cloud/src/cloud_module_test.c
cloud_msg should be used instead of could_msg_type.
=> modules: cloud: fix struct cloud_msg

.github/workflows/target-test.yml, tests/on_target/tests/test_functional/test_memfault.py
Add memfault test.
Test check that coredump are uploaded to memfault.
=> tests: on_target: add memfault test

tests/on_target/README.md, tests/on_target/tests/test_functional/test_location.py, tests/on_target/tests/test_functional/test_sampling.py, tests/on_target/utils/uart.py
Since cellular location method priority is no longer right after Wi-Fi, the location library will not combine Wi-Fi and cellular methods.
Due to this we need to update the test to not expect a combined location request.
Add additional checks to the same test to also verify that the device samples other sensor sources.
=> tests: nightly: Fix and add more tests

.github/workflows/build-and-target-test.yml, .github/workflows/target-test.yml, README.md, tests/on_target/tests/test_ppk/test_power.py
PPK test with readme badge and html plot.
=> tests: on_target: add pkk test

app/src/main.c, app/src/modules/cloud/cloud_module.c, app/src/modules/environmental/environmental.c, app/src/modules/led/led.c, app/src/modules/location/location.c
After state objects were made local and not static anymore, they need to be zero-initialized.
=> modules: Fix initialization of state objects

.github/workflows/build.yml
modem trace to memfault does not exist anymore.
=> workflows: build: no modem traces to memfault

docs/modules/network.md
Add network module documentation.
The state diagram is an initial version using Mermaid and needs to be improved on as it renders badly.
=> docs: Add network module documentation

.github/workflows/build.yml, .github/workflows/publish-symbol-files-to-memfault.yml, .github/workflows/target-test.yml
9151dk and thingy91x are currently racing for memfault upload. This should fix it.
=> workflows: fix memfault elf upload

.github/workflows/target-test.yml, tests/on_target/tests/conftest.py, tests/on_target/tests/test_functional/test_fota.py
Use env vars instead of runner vars
=> test: fota: Remove upload

tests/module/cloud/src/cloud_module_test.c
Use strnlen() instead of strlen(). It was safe in this case, but always nice to use strnlen() when possible.
Flagged by Sonarcloud.
=> tests: cloud: Use strnlen() for ssafety

.github/workflows/target-test.yml, tests/on_target/README.md
1.0.0 points to old github org.
Fix it with 1.0.1.
=> ci: use test docker 1.0.1

app/src/main.c
If configs coming from the cloud are malformed, cbor decoding fails. Device then bootloops. This is a temporary fix for that.
=> main: dont crash if cbor decoding fails

app/src/cbor/cbor_helper.c, app/src/cbor/cbor_helper.h, app/src/cbor/device_shadow.cddl, app/src/main.c, tests/module/main/src/checks.c, tests/module/main/src/checks.h, tests/module/main/src/main.c
The sub states in STATE_TRIGGERING have been updated to allow for a dedicated wait state, and to make it easier to have accurate intervals between samples.
Tests are updated, and we now also test that the correct interval is maintained over time.
=> main: Rework sub states in STATE_TRIGGERING

README.md, app/src/Kconfig.main, docs/modules/main.md
Add docs for main module and introduction to the template
=> Docs for main module

tests/module/main/src/checks.c, tests/module/main/src/checks.h, tests/module/main/src/main.c
- Add testcases for FOTA states
- Rename check_* helper functions to expect_*
=> tests: main: Add test cases for FOTA states

.github/workflows/build.yml
hex debug files is not created because of a typo.
=> workflows: small typo in build workflow

app/src/modules/network/network.c, app/src/modules/network/network.h, docs/modules/network.md, tests/module/network/src/main.c
=> modeules: network: Fix typo in message type

app/src/main.c, app/src/modules/cloud/cloud_module.c, app/src/modules/cloud/cloud_module.h, docs/modules/cloud.md, tests/module/cloud/src/cloud_module_test.c, tests/module/main/src/main.c
This pull request includes several changes to the cloud module and its associated documentation and tests. The most important changes include restructuring the state definitions, updating the documentation to provide more details on the module's functionality, and modifying test cases to reflect the changes in state handling.
* Refactored the hierarchical cloud module states for better readability and maintainability in `cloud_module.c`.
* Updated state handler comments to reflect the new state names. [[1]](diffhunk://#diff-19c5d76147d9c5e2277505a42dbff2d2fb8b5babb9b21b540ffa61db038fc1f5L330-R329) [[2]](diffhunk://#diff-19c5d76147d9c5e2277505a42dbff2d2fb8b5babb9b21b540ffa61db038fc1f5L430-R429)
* Enhanced the `docs/modules/cloud.md` with detailed descriptions of the module's …
=> Cloud docs and test fixes

app/src/modules/environmental/environmental.c, app/src/modules/led/led.c, docs/modules/button.md, docs/modules/environmental.md, docs/modules/led.md, docs/modules/power.md
This pull request includes several documentation updates and code changes across multiple modules to improve clarity and functionality. The most important changes include detailed explanations of module functionalities, message structures, and configuration options.
Documentation updates:
* [`docs/modules/environmental.md`](diffhunk://#diff-2b06183af9622c332a1427942ef0ec03e889d45e20dca6ff7d3401901f8e0df6L3-R64): Expanded the description of the Environmental module, including how it collects and communicates sensor data, message types, and configuration options.
* [`docs/modules/led.md`](diffhunk://#diff-4c9be35dd278b139c02b6d04ef5e2cf962041c2a5ac116d2e26001175fdec74cL1-R70): Enhanced the LED module documentation with details on message parameters, operation, and configuration options.
* …
=> Add documentation for power, LED and environmental modules

.github/workflows/target-test.yml
Dedicate a job to create the device matrix.
Thingy91x is default device.
9151dk is only run in nightly.
=> workflows: target_tests: new handling of matrix-device

app/src/common/app_common.h, app/src/main.c, app/src/modules/cloud/cloud_module.c
This pull request includes several updates to macros and subscriber definitions to improve code maintainability and readability. The most important changes involve the introduction of new macros for computing message sizes and updating subscriber definitions across multiple files.
* Added `SIZE_OF_TYPE` and `MAX_MSG_SIZE_FROM_LIST` macros to compute the maximum message size from a list of channel data types in `app/src/common/app_common.h`.
* Updated `MAX_MSG_SIZE` macro in `app/src/main.c` to use `MAX_MSG_SIZE_FROM_LIST` for calculating the maximum message size from the list of channels.
* Renamed `cloud` subscriber to `cloud_subscriber` and updated all references in `app/src/modules/cloud/cloud_module.c`. [[1]](diffhunk://#diff-19c5d76147d9c5e2277505a42dbff2d2fb8b5babb9b21b540ffa61db038f …
=> modules: Use X macros to subscribe to channels

app/src/modules/power/power.c
The PM actions should not cause a failure if they return -EALREADY. That only indicates that the desired state is already set.
=> modules: power: Do not fail on -EALREADY

.github/actions/build-step/action.yml, .github/workflows/build.yml, .github/workflows/ncsref-update.yaml, .github/workflows/target-test.yml
Update PR status
Move build details into action
=> Update PR status after test

.github/actions/build-step/action.yml, .github/workflows/attach_release_assets.yml, .github/workflows/build.yml, tests/on_target/tests/conftest.py, tests/on_target/tests/test_functional/test_memfault.py
MEMFAULT_CDR_MAX_ENCODED_METADATA_LEN controls maximum space for custom data header. Too long memfault fw type and version prefixes overflow it. Reducing those fixes the issue.
=> workflows: fix MEMFAULT_CDR_MAX_ENCODED_METADATA_LEN error

app/src/modules/cloud/cloud_module.c
Trigger an initial update to Memfault.
If a coredump is available, the Memfault LTE coredump library will take care of sending an initial update to Memfault upon connection.
After the initial update, the periodic Memfault update routine will update metrics every MEMFAULT_HTTP_PERIODIC_UPLOAD_INTERVAL_SECS (default: 3600 seconds).
=> modules: cloud: Trigger initial update to Memfault

README.md, docs/common/architecture.md
Fix typos, improve readability and shorten table of contents.
=> docs: Clean up in architecture docs

app/src/main.c, app/src/modules/cloud/CMakeLists.txt, app/src/modules/cloud/cloud.c, app/src/modules/cloud/cloud.h, app/src/modules/cloud/cloud_shell.c, docs/common/tooling_troubleshooting.md, docs/modules/cloud.md, docs/patches/magnetometer.patch, tests/module/cloud/CMakeLists.txt, tests/module/cloud/src/cloud_module_test.c, tests/module/main/src/main.c
To align with other modules, rename to cloud.
=> modules: cloud: Rename from cloud_module to cloud

app/src/modules/led/led.c
Gather led state variables into a struct.
=> modules: led: gather global variables in a common struct

app/src/modules/cloud/cloud.c, app/src/modules/environmental/environmental.c, app/src/modules/fota/fota.c, app/src/modules/location/location.c, app/src/modules/network/network.c, app/src/modules/power/power.c
Refactor and align code across modules.
=> app: refactor and align code

.github/workflows/target-test.yml
The firmware test for patched firmware is still run under the "normal" target test workflow.
=> ci: Remove separate test case for patched firmware

.github/workflows/target-test.yml, tests/on_target/tests/pytest.ini, tests/on_target/tests/test_functional/test_mqtt.py
This pull request makes changes to the testing configuration and test suite for on-target firmware tests. The most significant updates involve removing a specific test job for patched firmware, introducing a new pytest marker for MQTT-related tests, and applying this marker to an existing test.
* [`.github/workflows/target-test.yml`](diffhunk://#diff-70666865fb5fbc611086c2fd040c542baa487438cba3a2103e6a3749092c6a26L188-L208): Removed the "Test Patched Firmware" job from the GitHub Actions workflow. This job previously ran functional tests for patched firmware versions on the `thingy91x` device. The test is still run on-commit we just don't need a separate workflow for it.
* [`tests/on_target/tests/pytest.ini`](diffhunk://#diff-a4d0403b78b365b64667155d6be0c4a05c27ee3902f95efeed34f20c1912e0d2 …
=> CI: Improve test handling

app/src/modules/cloud/cloud.c
The error log referenced the wrong function name.
Feel free to fix-up into some other commit.
=> modules: cloud: fix error log

tests/on_target/tests/test_functional/test_memfault.py
Replace app.memfault.com with api.memfault.com endpoints. As recommended by Memfault.
The api.* endpoints are direct replacements for the app.* ones.
=> tests: memfault: align to api.memfault.com endpoint

tests/module/cloud/src/cloud_module_test.c, tests/module/cloud_mqtt/src/cloud_mqtt_test.c
zbus_chan_add_obs needs zbus_observer_node argument.
=> tests: module: fix sonarcloud

.github/workflows/build-and-target-test.yml, .github/workflows/ncsref-update.yaml, .github/workflows/target-test.yml
This changes fixes the logic for pushing nightly memory badges.
=> workflows: fix memory badges push

README.md, tests/on_target/scripts/parse_memory_stats.py
Add two badges in the readme that point to memory sunburst in gh-pages.
=> readme: add memory sunburst to readme

.github/actions/build-step/action.yml, .github/workflows/build-and-target-test.yml, .github/workflows/build.yml, .github/workflows/target-test.yml, README.md, scripts/sunburst_from_mem_report.py, tests/on_target/scripts/update_memory_badges.sh
Memory reports are now built and pushed nightly.
Also, single memory badge added, linking to split view of memory history and report.
=> workflows: add sunburst memory report to ci

app/src/modules/power/power.c
Traces are disabled on VBUS removed, but not enabled back when VBUS detected.
=> modules: power: fix bug

.github/workflows/compliance.yml
Compliance does not work with v3 or v4 editions.
=> workflow: compliance: Force install junitparser 2.8.0.

.github/workflows/zoomin-publish.yml, docs/common/location_services.md, docs/modules/environmental.md, docs/modules/location.md, docs/modules/power.md
Updated the workflow to publish doc on
every PR merge and minor doc fixes.
=> doc: doc publish on PR merge

app/src/modules/cloud/cloud.c
Use the Wi-Fi and cell info struct members only when the respective location methods are enabled.
=> cloud: Access Wi-Fi and cell struct members only when enabled

app/src/modules/cloud/cloud.c
- Remove logging of unhandled location messages
- Return early when a message has been processed
=> cloud: Remove redundant logging and processing

app/src/modules/location/location.c
Fix compilation errors when CONFIG_LOCATION_METHOD_GNSS is not enabled.
=> modules: location: Fix compile errors

app/src/modules/cloud/cloud.c, app/src/modules/environmental/Kconfig.environmental, app/src/modules/environmental/environmental.c, app/src/modules/environmental/environmental.h, app/src/modules/power/Kconfig.power, app/src/modules/power/power.c, app/src/modules/power/power.h, tests/module/cloud/src/cloud_module_test.c, tests/module/environmental/CMakeLists.txt, tests/module/environmental/src/environmental_module_test.c, tests/module/power/CMakeLists.txt, tests/module/power/src/power_module_test.c
This pull request introduces timestamp functionality for environmental and power sensor messages, enabling better tracking of data samples. It also updates related tests to validate timestamp handling and error scenarios.
* **Environmental Module:**
- Added a new `APP_ENVIRONMENTAL_TIMESTAMP` configuration option to include timestamps in environmental sensor messages.
- Modified `environmental.c` to retrieve and include timestamps in sensor messages when the configuration is enabled.
- Updated the `environmental_msg` struct to include a `timestamp` field.
* **Power Module:**
- Added a new `APP_POWER_TIMESTAMP` configuration option to include timestamps in power sensor messages.
- Modified `power.c` to retrieve and include timestamps in sensor messages when the configuration is enabled.
- …
=> Samples timestamps

tests/module/environmental/src/environmental_module_test.c, tests/module/power/src/power_module_test.c
Explicitly mark parameters as unused.
=> tests: Address Sonarcloud report on unused parameters

.github/workflows/target-test.yml, tests/on_target/tests/test_functional/test_fota.py
Update fota bundle to use relese 1.0.2 bin file.
Also, APP_BUNDLEID should be vars., not env., in workflow file.
=> tests: on_target: new app fota bundle

app/src/modules/power/power.c
Fixed a Valgrind error where an uninitialized sensor_value struct in charger_read_sensors() was being used in conditional operations. Added zero-initialization of the struct to ensure all fields have defined values before being passed to sensor_channel_get().
=> modules: power: Initialize struct to prevent uninitialized value usage

app/boards/nrf9151dk_nrf9151_ns.overlay, app/boards/thingy91x_nrf9151_ns.overlay, docs/common/tooling_troubleshooting.md
- Add section for dumping modem traces from flash to UART
- Add table of contents for better navigation
- Improve formatting and fix typos throughout the document
- Add missing DTS entries for modem tracing
=> docs: Add modem tracing instructions

README.md, docs/common/getting_started.md, docs/common/provisioning.md
Remove reference to Quickstart app for now. Will be readded once Quickstart support ATT.
=> docs: Remove reference to Quickstart app for now

.github/actions/build-step/action.yml
Remove external antenna configuration for the DK in CI as it was applied for all images, even prod builds released for the DK in releases.
=> ci: revert board-specific config for nrf9151dk

app/src/main.c, tests/module/main/src/main.c
In passthrough mode the device was sampling even though the device was disconnected.
Address this issue by stopping the sampling timers when entering passthrough_disconnected mode.
=> src: main: fix sampling misbehavior
